### ISSUE TITLE
Can't initialise the scanner

### ISSUE THREAD

**Issue by daniloMogin** [hadeeb/simple-barcode-scanner#23]
I'm getting this error while trying to initialize the scanner.

import BarcodeScanner from "simple-barcode-scanner";
const scanner = BarcodeScanner(); <- this is what is producing the error

`ReferenceError: document is not defined
    at module.exports (D:\sources\BIzdavanje\server\node_modules\simple-barcode-scanner\dist\index.js:1:95)
    at Object.<anonymous> (D:\sources\BIzdavanje\server\dist\src\server.js:33:54)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47`

**Comment by hadeeb** [comment]
This module is supposed to be used only in browser-like environments.
Looks like you are trying to use it from a nodejs application. It is not supported.
